// Generated by CoffeeScript 1.3.3
(function() {
  var ImageUtils;

  ImageUtils = {
    getExtremes: function() {
      var i, index, max, min, value, _i, _j, _len, _ref, _ref1, _ref2, _ref3;
      if ((this.min != null) && (this.max != null)) {
        return [this.min, this.max];
      }
      _ref = this.data;
      for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
        value = _ref[index];
        if (isNaN(value)) {
          continue;
        }
        _ref1 = [value, value], min = _ref1[0], max = _ref1[1];
        break;
      }
      for (i = _j = index, _ref2 = this.data.length - 1; index <= _ref2 ? _j <= _ref2 : _j >= _ref2; i = index <= _ref2 ? ++_j : --_j) {
        value = this.data[i];
        if (isNaN(value)) {
          continue;
        }
        if (value < min) {
          min = value;
        }
        if (value > max) {
          max = value;
        }
      }
      _ref3 = [min, max], this.min = _ref3[0], this.max = _ref3[1];
      return [this.min, this.max];
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = ImageUtils;
  }

}).call(this);
