// Generated by CoffeeScript 1.3.3
(function() {
  var HDU;

  HDU = (function() {

    function HDU(header, data) {
      this.header = header;
      this.data = data;
    }

    HDU.prototype.hasData = function() {
      if (this.data != null) {
        return true;
      } else {
        return false;
      }
    };

    HDU.prototype.getCard = function(key) {
      return this.header[key];
    };

    return HDU;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = HDU;
  }

}).call(this);
